spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: mq-rest-adapter
  profiles:
    include: toggle

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000